import { useMemo, useState } from "react";
import {
  ArchiveIcon, ArrowLeftIcon, BarChartIcon, BellIcon, CameraIcon, CheckCircledIcon,
  ChevronRightIcon, Cross2Icon, DashboardIcon, GearIcon, HeartIcon, HomeIcon,
  MagnifyingGlassIcon, MinusIcon, MixerHorizontalIcon, MobileIcon, Pencil2Icon,
  PersonIcon, PlusIcon, ReaderIcon, RocketIcon, SewingPinIcon, Share2Icon,
  StarFilledIcon, TrashIcon
} from "@radix-ui/react-icons";
import { MobileScroll, KeyboardInput } from "./mobile";

type Screen = "login" | "onboarding" | "home" | "catalog" | "product" | "cart" | "delivery" | "payment" | "success" | "products" | "productForm" | "orders" | "orderDetail" | "customers" | "stats" | "profile" | "settings";
type Product = { id: number; name: string; price: number; stock: number; image: string; category: string };

const products: Product[] = [
  { id: 1, name: "Chemise imprimée", price: 7500, stock: 15, image: "/assets/products/shirt.png", category: "Vêtements" },
  { id: 2, name: "Baskets Nike Air Max", price: 35000, stock: 8, image: "/assets/products/shoes.png", category: "Chaussures" },
  { id: 3, name: "Sac à main luxe", price: 20000, stock: 5, image: "/assets/products/bag.png", category: "Accessoires" },
  { id: 4, name: "Montre classique", price: 15000, stock: 12, image: "/assets/products/watch.png", category: "Accessoires" },
];
const money = (n: number) => `${n.toLocaleString("fr-FR")} FCFA`;

function TopBar({ title, back, action }: { title: string; back?: () => void; action?: React.ReactNode }) {
  return <header className="topbar">{back ? <button className="icon-btn" onClick={back} aria-label="Retour"><ArrowLeftIcon /></button> : <span className="top-spacer" />}<strong>{title}</strong><span className="top-action">{action}</span></header>;
}

function BottomNav({ active, go }: { active: string; go: (s: Screen) => void }) {
  const items: [Screen, string, React.ReactNode][] = [["home","Accueil",<HomeIcon/>],["products","Produits",<ArchiveIcon/>],["orders","Commandes",<ReaderIcon/>],["stats","Stats",<BarChartIcon/>],["profile","Profil",<PersonIcon/>]];
  return <nav className="bottom-nav">{items.map(([id,label,icon])=><button key={id} className={active===id?"active":""} onClick={()=>go(id)}>{icon}<span>{label}</span></button>)}</nav>;
}

function Login({ go }: { go: (s: Screen) => void }) {
  return <div className="auth-page"><div className="brand-mark"><MobileIcon /></div><h1>SmartShop</h1><h2>WhatsApp</h2><p>Votre boutique. Vos clients.<br/>Vos ventes. Sur WhatsApp.</p><div className="auth-card"><label>Téléphone ou e-mail</label><KeyboardInput aria-label="Téléphone ou e-mail" placeholder="+237 6 95 12 34 56"/><label>Mot de passe</label><KeyboardInput aria-label="Mot de passe" placeholder="••••••••"/><button className="primary" onClick={()=>go("home")}>Se connecter</button><button className="text-button" onClick={()=>go("onboarding")}>Créer ma boutique</button></div><small>Simple, sécurisé et pensé pour le Cameroun.</small></div>;
}

function Onboarding({ go }: { go: (s: Screen) => void }) {
  const [step,setStep]=useState(1);
  return <div className="page"><TopBar title="Créer ma boutique" back={()=>step>1?setStep(step-1):go("login")}/><section className="content onboarding"><div className="steps"><span className="done">1</span><i/><span className={step>1?"done":""}>2</span><i/><span className={step>2?"done":""}>3</span></div><p className="eyebrow">ÉTAPE {step} SUR 3</p><h1>{step===1?"Parlez-nous de votre boutique":step===2?"Configurez les commandes":"Votre boutique est prête"}</h1>{step===1&&<div className="form"><label>Nom de la boutique</label><KeyboardInput aria-label="Nom boutique" placeholder="MK Fashion Store"/><label>Secteur</label><button className="select">Mode & accessoires <ChevronRightIcon/></button><label>Ville</label><KeyboardInput aria-label="Ville" placeholder="Yaoundé"/></div>}{step===2&&<div className="form"><label>Numéro WhatsApp</label><KeyboardInput aria-label="WhatsApp" placeholder="+237 6 95 12 34 56"/><label>Frais de livraison</label><KeyboardInput aria-label="Livraison" placeholder="2 000 FCFA"/><div className="choice selected"><MobileIcon/><span><b>Mobile Money</b><small>MTN MoMo et Orange Money</small></span><CheckCircledIcon/></div></div>}{step===3&&<div className="ready"><CheckCircledIcon/><h2>MK Fashion Store</h2><p>Votre lien est prêt à être partagé.</p><div className="link">smartshop.cm/mk-fashion <Share2Icon/></div></div>}<button className="primary sticky-cta" onClick={()=>step<3?setStep(step+1):go("home")}>{step<3?"Continuer":"Accéder au tableau de bord"}</button></section></div>;
}

function Home({ go }: { go: (s: Screen) => void }) {
  return <div className="page merchant"><section className="hero"><div className="hero-row"><div><small>Bonjour,</small><h1>Michel <span>👋</span></h1><p>Tableau de bord</p></div><button className="icon-btn light"><BellIcon/><i className="dot"/></button></div><div className="revenue"><small>Chiffre d’affaires</small><div><b>356 800</b> FCFA</div><em>+ 26% ce mois</em><svg viewBox="0 0 100 45" aria-hidden="true"><polyline points="2,39 18,30 34,31 52,16 70,12 88,2 98,5" fill="none" stroke="#f4d234" strokeWidth="3"/></svg></div></section><section className="content dashboard"><div className="kpis"><div><small>Commandes</small><b>28</b><span>En cours</span></div><div><small>Produits</small><b>56</b><span>En stock</span></div><div><small>Clients</small><b>124</b><span>Total</span></div></div><div className="section-title"><b>Commandes récentes</b><button onClick={()=>go("orders")}>Voir tout</button></div><div className="order-list compact">{[["#2550","59 500","En attente"],["#2549","25 000","Confirmée"],["#2548","12 500","Livrée"]].map(x=><button key={x[0]} onClick={()=>go("orderDetail")}><span className="thumb-icon"><ArchiveIcon/></span><span><b>Commande {x[0]}</b><small>18 Mai 2024</small></span><strong>{x[1]} FCFA<em>{x[2]}</em></strong></button>)}</div><button className="primary" onClick={()=>go("productForm")}><PlusIcon/> Ajouter un produit</button></section><BottomNav active="home" go={go}/></div>;
}

function Catalog({ go }: { go: (s: Screen) => void }) {
  const [filter,setFilter]=useState("Tous");
  const shown=filter==="Tous"?products:products.filter(p=>p.category===filter);
  return <div className="page"><TopBar title="Catalogue" back={()=>go("home")} action={<button className="icon-btn" onClick={()=>go("cart")}><ArchiveIcon/><i className="badge">3</i></button>}/><section className="content catalog"><div className="search"><MagnifyingGlassIcon/><KeyboardInput aria-label="Rechercher" placeholder="Rechercher un produit..."/></div><div className="chips">{["Tous","Vêtements","Chaussures","Accessoires"].map(f=><button className={filter===f?"active":""} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div><div className="product-grid">{shown.map(p=><article key={p.id} onClick={()=>go("product")}><img src={p.image} alt={p.name}/><h3>{p.name}</h3><b>{money(p.price)}</b><button onClick={(e)=>{e.stopPropagation();go("cart")}}><MobileIcon/> Commander</button></article>)}</div></section><BottomNav active="products" go={go}/></div>;
}

function ProductView({ go }: { go: (s: Screen) => void }) {
  const [size,setSize]=useState(42); const [qty,setQty]=useState(1);
  return <div className="page"><TopBar title="1/5" back={()=>go("catalog")} action={<button className="icon-btn"><HeartIcon/></button>}/><section className="content product-view"><img className="product-hero" src="/assets/products/shoes.png" alt="Baskets Nike Air Max 270"/><h1>Baskets Nike Air Max 270</h1><div className="price">35 000 <small>FCFA</small></div><div className="rating"><StarFilledIcon/> 4.6 <small>(124 avis)</small><span>● En stock</span></div><p>Confort exceptionnel et style moderne pour toutes vos activités. Disponible en plusieurs tailles.</p><b>Taille</b><div className="sizes">{[39,40,41,42,43,44].map(s=><button className={size===s?"active":""} onClick={()=>setSize(s)} key={s}>{s}</button>)}</div><b>Quantité</b><div className="counter"><button onClick={()=>setQty(Math.max(1,qty-1))}><MinusIcon/></button><span>{qty}</span><button onClick={()=>setQty(qty+1)}><PlusIcon/></button></div><button className="primary sticky-cta" onClick={()=>go("cart")}>Ajouter au panier</button></section></div>;
}

function Cart({ go }: { go: (s: Screen) => void }) {
  return <div className="page"><TopBar title="Mon panier" action={<button className="text-button">Modifier</button>}/><section className="content cart"><CartLine p={products[1]}/><CartLine p={products[0]}/><CartLine p={products[3]}/><button className="delivery-row" onClick={()=>go("delivery")}><RocketIcon/><span><b>Livraison</b><small>Yaoundé centre</small></span><strong>2 000 FCFA</strong><ChevronRightIcon/></button><Summary/><button className="primary sticky-cta" onClick={()=>go("delivery")}>Passer à la commande</button></section><BottomNav active="" go={go}/></div>;
}
function CartLine({p}:{p:Product}) { return <div className="cart-line"><img src={p.image} alt=""/><span><b>{p.name}</b><small>{p.category}</small><strong>{money(p.price)}</strong></span><button className="icon-btn"><TrashIcon/></button><div className="mini-counter"><button>−</button><span>1</span><button>+</button></div></div> }
function Summary(){return <div className="summary"><div><span>Sous-total</span><b>57 500 FCFA</b></div><div><span>Livraison</span><b>2 000 FCFA</b></div><div className="total"><span>Total</span><b>59 500 FCFA</b></div></div>}

function Delivery({go}:{go:(s:Screen)=>void}){return <div className="page"><TopBar title="Livraison" back={()=>go("cart")}/><section className="content checkout"><h2>Où devons-nous livrer ?</h2><div className="form"><label>Nom complet</label><KeyboardInput aria-label="Nom" placeholder="Michel Kanga"/><label>Téléphone</label><KeyboardInput aria-label="Téléphone" placeholder="+237 6 95 12 34 56"/><label>Ville et quartier</label><KeyboardInput aria-label="Adresse" placeholder="Yaoundé, Bastos"/><label>Indications</label><KeyboardInput aria-label="Indications" placeholder="Immeuble blanc, portail vert"/></div><div className="choice selected"><RocketIcon/><span><b>Livraison à domicile</b><small>2 000 FCFA · 24 à 48 h</small></span><CheckCircledIcon/></div><div className="choice"><ArchiveIcon/><span><b>Retrait en boutique</b><small>Gratuit · dès aujourd’hui</small></span></div><button className="primary sticky-cta" onClick={()=>go("payment")}>Continuer vers le paiement</button></section></div>}

function Payment({go}:{go:(s:Screen)=>void}){const [m,setM]=useState("mtn");return <div className="page"><TopBar title="Paiement" back={()=>go("delivery")}/><section className="content checkout"><h3>Choisissez votre moyen de paiement</h3>{[["mtn","MTN Mobile Money","Payer avec MTN MoMo"],["orange","Orange Money","Payer avec Orange Money"],["cash","Paiement à la livraison","Payez en espèces à la réception"]].map(x=><button className={`payment-option ${m===x[0]?"selected":""}`} onClick={()=>setM(x[0])} key={x[0]}><span className={`pay-logo ${x[0]}`}>{x[0]==="cash"?<RocketIcon/>:x[0].toUpperCase()}</span><span><b>{x[1]}</b><small>{x[2]}</small></span>{m===x[0]?<CheckCircledIcon/>:<i/>}</button>)}<h3>Résumé de la commande</h3><Summary/><button className="primary sticky-cta" onClick={()=>go("success")}>Payer 59 500 FCFA</button><p className="secure">Paiement 100% sécurisé</p></section></div>}

function Success({go}:{go:(s:Screen)=>void}){return <div className="page"><TopBar title="" back={()=>go("payment")}/><section className="content success"><div className="success-icon"><CheckCircledIcon/></div><h1>Commande confirmée !</h1><p>Votre commande <b>#2550</b> a été confirmée et envoyée sur WhatsApp.</p><div className="sent"><span>Envoyé à :</span><b>+237 6 95 12 34 56</b><MobileIcon/></div><p>Vous recevrez bientôt un message avec les détails de votre commande.</p><button className="primary" onClick={()=>window.open("https://wa.me/237695123456?text=Commande%20%232550", "_blank")}><MobileIcon/> Ouvrir WhatsApp</button><button className="secondary" onClick={()=>go("orderDetail")}>Voir ma commande</button></section></div>}

function Products({go}:{go:(s:Screen)=>void}){const [query,setQuery]=useState("");return <div className="page"><TopBar title="Mes produits" action={<button className="icon-btn" onClick={()=>go("productForm")}><PlusIcon/></button>}/><section className="content list-page"><div className="search"><MagnifyingGlassIcon/><KeyboardInput aria-label="Rechercher produit" placeholder="Rechercher un produit..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="chips"><button className="active">Tous (56)</button><button>En stock (42)</button><button>Rupture (14)</button></div>{products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).map(p=><button className="manage-row" key={p.id} onClick={()=>go("productForm")}><img src={p.image} alt=""/><span><b>{p.name}</b><strong>{money(p.price)}</strong><small>Stock : {p.stock}</small></span><i className="toggle on"/></button>)}</section><BottomNav active="products" go={go}/></div>}

function ProductForm({go}:{go:(s:Screen)=>void}){const [saved,setSaved]=useState(false);const [image,setImage]=useState<string|null>(null);const [uploading,setUploading]=useState(false);const handleImageUpload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setUploading(true);try{const formData=new FormData();formData.append("file",file);const res=await fetch("/api/uploads/product-image",{method:"POST",body:formData});const data=await res.json();if(data.success)setImage(data.url);}catch(err){console.error("Upload failed:",err);}finally{setUploading(false);}};return <div className="page"><TopBar title="Nouveau produit" back={()=>go("products")} action={<button className="text-button" onClick={()=>{setSaved(true);setTimeout(()=>go("products"),700)}}>Enregistrer</button>}/><section className="content product-form">{image?<div className="photo-preview"><img src={image} alt="Aperçu"/><button className="remove-photo" onClick={()=>setImage(null)}>✕</button></div>:<label htmlFor="photo-input" className="photo" style={{cursor:"pointer"}}><CameraIcon/><b>Ajouter des photos</b><small>Jusqu’à 5 images</small>{uploading&&<small style={{color:"#007a49"}}>Chargement...</small>}</label>}<input id="photo-input" type="file" accept="image/*" onChange={handleImageUpload} style={{display:"none"}}/><div className="form"><label>Nom du produit</label><KeyboardInput aria-label="Produit" placeholder="Ex. Robe en wax"/><label>Description</label><KeyboardInput aria-label="Description" placeholder="Décrivez le produit..."/><div className="two-cols"><div><label>Prix</label><KeyboardInput aria-label="Prix" placeholder="15 000"/></div><div><label>Stock</label><KeyboardInput aria-label="Stock" placeholder="10"/></div></div><label>Catégorie</label><button className="select">Vêtements <ChevronRightIcon/></button><label>Variantes</label><button className="select">Ajouter taille ou couleur <PlusIcon/></button></div>{saved&&<div className="toast"><CheckCircledIcon/> Produit enregistré</div>}<button className="primary sticky-cta" onClick={()=>go("products")}>Publier le produit</button></section></div>}

const orderData=[["#2550","18 Mai 2024 · 14:30","59 500","En attente"],["#2549","18 Mai 2024 · 10:15","25 000","Confirmée"],["#2548","17 Mai 2024 · 16:45","12 500","Livrée"],["#2547","17 Mai 2024 · 09:20","8 000","Annulée"],["#2546","16 Mai 2024 · 18:00","15 000","Livrée"]];
function Orders({go}:{go:(s:Screen)=>void}){const [filter,setFilter]=useState("Toutes");return <div className="page"><TopBar title="Commandes"/><section className="content list-page"><div className="search"><MagnifyingGlassIcon/><KeyboardInput aria-label="Commande" placeholder="Rechercher une commande..."/></div><div className="chips">{["Toutes","En attente","Confirmées","Livrées"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="order-list">{orderData.filter(o=>filter==="Toutes"||o[3].startsWith(filter.slice(0,-1))).map(o=><button onClick={()=>go("orderDetail")} key={o[0]}><span><b>{o[0]}</b><small>{o[1]}</small></span><strong>{o[2]} FCFA<em className={o[3].toLowerCase().replace(" ","-")}>{o[3]}</em></strong></button>)}</div></section><BottomNav active="orders" go={go}/></div>}

function OrderDetail({go}:{go:(s:Screen)=>void}){const [status,setStatus]=useState("En attente");return <div className="page"><TopBar title="Commande #2550" back={()=>go("orders")} action={<button className="icon-btn"><Share2Icon/></button>}/><section className="content detail"><div className="status-card"><small>STATUT ACTUEL</small><b>{status}</b><span>18 mai 2024 à 14:30</span></div><h3>Client</h3><button className="client-card" onClick={()=>go("customers")}><span className="avatar">MK</span><span><b>Marie K.</b><small>+237 6 77 45 21 09</small></span><ChevronRightIcon/></button><h3>Articles</h3><CartLine p={products[1]}/><CartLine p={products[0]}/><h3>Livraison</h3><div className="info-card"><SewingPinIcon/><span><b>Bastos, Yaoundé</b><small>Immeuble blanc, portail vert</small></span></div><Summary/><label>Mettre à jour le statut</label><div className="chips wrap">{["Confirmée","En préparation","En livraison","Livrée"].map(x=><button className={status===x?"active":""} onClick={()=>setStatus(x)} key={x}>{x}</button>)}</div><button className="primary" onClick={()=>setStatus("Confirmée")}>Confirmer la commande</button></section></div>}

function Customers({go}:{go:(s:Screen)=>void}){return <div className="page"><TopBar title="Clients" back={()=>go("profile")}/><section className="content list-page"><div className="search"><MagnifyingGlassIcon/><KeyboardInput aria-label="Client" placeholder="Rechercher un client..."/></div><div className="customer-summary"><div><b>124</b><span>clients</span></div><div><b>18</b><span>nouveaux ce mois</span></div></div>{[["MK","Marie K.","8 commandes · 185 000 FCFA"],["JN","Jean N.","5 commandes · 92 500 FCFA"],["SA","Sarah A.","3 commandes · 67 000 FCFA"],["PM","Paul M.","2 commandes · 31 500 FCFA"]].map(c=><button className="client-card" key={c[1]}><span className="avatar">{c[0]}</span><span><b>{c[1]}</b><small>{c[2]}</small></span><ChevronRightIcon/></button>)}</section></div>}

function Stats({go}:{go:(s:Screen)=>void}){return <div className="page"><TopBar title="Statistiques" action={<button className="period">Ce mois⌄</button>}/><section className="content stats"><div className="chart-card"><small>Chiffre d’affaires</small><h1>356 800 <small>FCFA</small></h1><em>+ 26% par rapport au mois dernier</em><svg viewBox="0 0 340 125"><polyline points="2,110 30,96 58,102 86,84 114,52 142,58 170,75 198,69 226,42 254,30 282,35 312,12 338,3" fill="none" stroke="#07834f" strokeWidth="4"/><line x1="0" y1="114" x2="340" y2="114" stroke="#dde5e1"/></svg><div className="axis"><span>1 Mai</span><span>10 Mai</span><span>20 Mai</span><span>31 Mai</span></div></div><h3>Aperçu</h3><div className="stat-grid"><div><span>Commandes</span><b>28</b><em>+ 18%</em></div><div><span>Produits vendus</span><b>96</b><em>+ 22%</em></div><div><span>Clients</span><b>124</b><em>+ 15%</em></div><div><span>Panier moyen</span><b>12 740 <small>FCFA</small></b><em>+ 8%</em></div></div><h3>Meilleures ventes</h3>{products.slice(0,3).map((p,i)=><div className="rank" key={p.id}><b>{i+1}</b><img src={p.image} alt=""/><span><strong>{p.name}</strong><small>{22-i*4} ventes</small></span><em>{money(p.price*(22-i*4))}</em></div>)}</section><BottomNav active="stats" go={go}/></div>}


function Profile({go}:{go:(s:Screen)=>void}){return <div className="page"><section className="profile-hero"><img src="/assets/products/avatar.png" alt="Michel Kanga"/><h2>Michel Kanga <small>Pro</small></h2><p>Boutique : MK Fashion Store<br/>Yaoundé, Cameroun</p></section><section className="profile-menu">{[["catalog",<HomeIcon/>,"Voir ma boutique client"],["settings",<ArchiveIcon/>,"Informations de la boutique"],["settings",<MobileIcon/>,"Mes moyens de paiement"],["settings",<SewingPinIcon/>,"Adresse de livraison"],["settings",<GearIcon/>,"Paramètres de la boutique"],["settings",<StarFilledIcon/>,"Abonnement · Plan Pro"],["customers",<PersonIcon/>,"Clients"],["settings",<ReaderIcon/>,"Aide & Support"]].map((x,i)=><button key={i} onClick={()=>go(x[0] as Screen)}>{x[1]}<span>{x[2]}</span><ChevronRightIcon/></button>)}<button className="logout" onClick={()=>go("login")}><Cross2Icon/><span>Se déconnecter</span></button></section><BottomNav active="profile" go={go}/></div>}

function Settings({go}:{go:(s:Screen)=>void}){const [open,setOpen]=useState(true);return <div className="page"><TopBar title="Paramètres boutique" back={()=>go("profile")}/><section className="content settings"><h3>Identité</h3><div className="shop-logo"><ArchiveIcon/><span><b>MK Fashion Store</b><small>smartshop.cm/mk-fashion</small></span><button className="icon-btn"><Pencil2Icon/></button></div><div className="form"><label>Description</label><KeyboardInput aria-label="Description boutique" value="Mode, chaussures et accessoires à Yaoundé" readOnly/><label>Numéro WhatsApp</label><KeyboardInput aria-label="Numéro WhatsApp" value="+237 6 95 12 34 56" readOnly/></div><h3>Disponibilité</h3><div className="setting-row"><span><b>Boutique ouverte</b><small>Les clients peuvent commander</small></span><button className={`toggle ${open?"on":""}`} onClick={()=>setOpen(!open)}/></div><div className="setting-row"><span><b>Commande minimum</b><small>Aucune limite</small></span><ChevronRightIcon/></div><div className="setting-row"><span><b>Zones de livraison</b><small>Yaoundé · 2 000 FCFA</small></span><ChevronRightIcon/></div><h3>Apparence</h3><div className="theme-row"><button className="swatch green selected"/><button className="swatch blue"/><button className="swatch brown"/></div><button className="primary">Enregistrer les modifications</button></section></div>}

export default function Prototype() {
  const [screen,setScreen]=useState<Screen>("home");
  const view=useMemo(()=>({login:<Login go={setScreen}/>,onboarding:<Onboarding go={setScreen}/>,home:<Home go={setScreen}/>,catalog:<Catalog go={setScreen}/>,product:<ProductView go={setScreen}/>,cart:<Cart go={setScreen}/>,delivery:<Delivery go={setScreen}/>,payment:<Payment go={setScreen}/>,success:<Success go={setScreen}/>,products:<Products go={setScreen}/>,productForm:<ProductForm go={setScreen}/>,orders:<Orders go={setScreen}/>,orderDetail:<OrderDetail go={setScreen}/>,customers:<Customers go={setScreen}/>,stats:<Stats go={setScreen}/>,profile:<Profile go={setScreen}/>,settings:<Settings go={setScreen}/>}),[]);
  return <MobileScroll className="app-screen"><main className="smartshop" data-testid="smartshop-app">{view[screen]}</main></MobileScroll>;
}
